#ifndef _ASSETS_TAG_H
#define _ASSETS_TAG_H

typedef enum SFXTag {
    PLAYER_MOVE_SFX = 0,
    PLAYER_BOOST_SFX,
    PLAYER_READY_SFX,
    PLAYER_WARN_SFX,
    PLAYER_DEATH_SFX,
    WEAPON1_FIRE_SFX,
    WEAPON2_FIRE_SFX,
    WEAPON3_FIRE_SFX,
    WEAPON1_HIT_SFX,
    WEAPON2_HIT_SFX,
    WEAPON3_HIT_SFX,
    ENEMY_DEAD_SFX,
    COLLECT_SFX,
    BUYING_SFX,
    PAUSE_SFX,
    RANKUP_SFX,
    ENDING_SFX,
} SFXTag_t;
#endif
